# Generated by Django 4.1.2 on 2022-10-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="age",
            field=models.CharField(default="", max_length=3),
            preserve_default=False,
        ),
    ]
