# Generated by Django 4.1.2 on 2022-10-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cine", "0002_client_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client", name="name", field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="movie", name="director", field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="movie", name="name", field=models.CharField(max_length=40),
        ),
    ]
